<script setup lang="ts"></script>
<template>
  <div class="flex flex-col max-w-5xl p-4">
    <h1 class="h1">Theme Generator</h1>
    <header class="header">
      <section class="section">
        <p>
          Vuetiful is fully compatible with themes generated by
          <a class="anchor" href="https://themes.skeleton.dev/">
            https://themese.skeleton.dev/
            </a>.
        </p>
        <p>Detailed guide coming soon.</p>
      </section>
    </header>
  </div>
</template>
